--- 
- hosts: test-servers
  tasks:
   - name: install httpd and vsftpd 
     yum:
      name: "{{packages}}"
      state: absent 
     vars:
      packages:
       - httpd
       - httpd-tools
       - vsftpd
      
